-- seed-cities-expansion.sql
-- Generated by backend/expand-cities.js from StatsCan table 17-10-0135-01
-- Generated: 2026-08-12
-- 120 new CMAs/CAs not already covered by the existing 42 cities
-- NOTE: ON DUPLICATE KEY UPDATE only takes effect if cma_code has a UNIQUE
-- index — add one (ALTER TABLE cities_meta ADD UNIQUE KEY (cma_code);) before
-- re-running this file, or re-runs will insert duplicate rows.

-- ── cities_meta ──────────────────────────────────────────────────────────
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_52', 'Ottawa - Gatineau', 'Ontario', 'ON', 1498610)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_53', 'Ottawa - Gatineau', 'Ontario', 'ON', 1143407)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_54', 'Ottawa - Gatineau', 'Quebec', 'QC', 355203)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_2', 'Bay Roberts', 'Newfoundland and Labrador', 'NL', 11087)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_3', 'Grand Falls-Windsor', 'Newfoundland and Labrador', 'NL', 14411)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_4', 'Gander', 'Newfoundland and Labrador', 'NL', 13667)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_5', 'Corner Brook', 'Newfoundland and Labrador', 'NL', 31840)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_6', 'Charlottetown', 'Prince Edward Island', 'PE', 86865)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_7', 'Summerside', 'Prince Edward Island', 'PE', 18938)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_9', 'Kentville', 'Nova Scotia', 'NS', 29683)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_10', 'Truro', 'Nova Scotia', 'NS', 48282)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_11', 'New Glasgow', 'Nova Scotia', 'NS', 35717)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_12', 'Cape Breton', 'Nova Scotia', 'NS', 98821)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_16', 'Bathurst', 'New Brunswick', 'NB', 31999)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_17', 'Miramichi', 'New Brunswick', 'NB', 28749)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_18', 'Edmundston', 'New Brunswick', 'NB', 24132)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_19', 'Campbellton', 'New Brunswick', 'NB', 15896)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_20', 'Campbellton', 'New Brunswick', 'NB', 12943)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_21', 'Campbellton', 'Quebec', 'QC', 2953)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_22', 'Matane', 'Quebec', 'QC', 17748)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_23', 'Rimouski', 'Quebec', 'QC', 57013)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_24', 'Rivière-du-Loup', 'Quebec', 'QC', 29979)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_25', 'Baie-Comeau', 'Quebec', 'QC', 26667)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_27', 'Alma', 'Quebec', 'QC', 33195)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_28', 'Dolbeau-Mistassini', 'Quebec', 'QC', 15317)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_29', 'Sept-Îles', 'Quebec', 'QC', 28202)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_31', 'Sainte-Marie', 'Quebec', 'QC', 13608)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_32', 'Saint-Georges', 'Quebec', 'QC', 33975)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_33', 'Thetford Mines', 'Quebec', 'QC', 29290)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_35', 'Cowansville', 'Quebec', 'QC', 16065)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_36', 'Victoriaville', 'Quebec', 'QC', 51541)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_38', 'Shawinigan', 'Quebec', 'QC', 56876)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_40', 'Granby', 'Quebec', 'QC', 93332)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_41', 'Saint-Hyacinthe', 'Quebec', 'QC', 62557)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_42', 'Sorel-Tracy', 'Quebec', 'QC', 43038)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_43', 'Joliette', 'Quebec', 'QC', 54072)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_45', 'Salaberry-de-Valleyfield', 'Quebec', 'QC', 44508)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_46', 'Lachute', 'Quebec', 'QC', 14537)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_47', 'Val-d''Or', 'Quebec', 'QC', 34687)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_48', 'Rouyn-Noranda', 'Quebec', 'QC', 43075)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_49', 'Hawkesbury', 'Ontario', 'ON', 12519)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_50', 'Hawkesbury', 'Ontario', 'ON', 10611)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_51', 'Hawkesbury', 'Quebec', 'QC', 1908)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_55', 'Cornwall', 'Ontario', 'ON', 63160)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_56', 'Arnprior', 'Ontario', 'ON', 18396)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_57', 'Carleton Place', 'Ontario', 'ON', 40644)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_58', 'Brockville', 'Ontario', 'ON', 41217)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_59', 'Pembroke', 'Ontario', 'ON', 23415)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_60', 'Petawawa', 'Ontario', 'ON', 19902)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_63', 'Cobourg', 'Ontario', 'ON', 20258)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_64', 'Port Hope', 'Ontario', 'ON', 18109)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_66', 'Kawartha Lakes', 'Ontario', 'ON', 83356)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_67', 'Centre Wellington', 'Ontario', 'ON', 32889)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_69', 'Ingersoll', 'Ontario', 'ON', 14521)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_75', 'Woodstock', 'Ontario', 'ON', 49819)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_76', 'Tillsonburg', 'Ontario', 'ON', 18252)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_77', 'Norfolk', 'Ontario', 'ON', 73166)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_79', 'Stratford', 'Ontario', 'ON', 34643)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_81', 'Chatham-Kent', 'Ontario', 'ON', 109051)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_82', 'Leamington', 'Ontario', 'ON', 54556)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_84', 'Sarnia', 'Ontario', 'ON', 102216)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_85', 'Wasaga Beach', 'Ontario', 'ON', 25852)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_86', 'Owen Sound', 'Ontario', 'ON', 34606)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_87', 'Collingwood', 'Ontario', 'ON', 25722)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_89', 'Orillia', 'Ontario', 'ON', 35272)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_90', 'Midland', 'Ontario', 'ON', 41281)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_91', 'North Bay', 'Ontario', 'ON', 77037)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_93', 'Elliot Lake', 'Ontario', 'ON', 11696)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_94', 'Timmins', 'Ontario', 'ON', 42675)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_95', 'Sault Ste. Marie', 'Ontario', 'ON', 81158)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_97', 'Kenora', 'Ontario', 'ON', 15990)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_99', 'Winkler', 'Manitoba', 'MB', 35666)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_100', 'Steinbach', 'Manitoba', 'MB', 15997)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_101', 'Portage la Prairie', 'Manitoba', 'MB', 13647)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_102', 'Brandon', 'Manitoba', 'MB', 63822)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_103', 'Thompson', 'Manitoba', 'MB', 14421)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_105', 'Yorkton', 'Saskatchewan', 'SK', 19399)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_106', 'Moose Jaw', 'Saskatchewan', 'SK', 35361)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_107', 'Swift Current', 'Saskatchewan', 'SK', 19438)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_109', 'North Battleford', 'Saskatchewan', 'SK', 19416)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_110', 'Prince Albert', 'Saskatchewan', 'SK', 46104)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_111', 'Estevan', 'Saskatchewan', 'SK', 13148)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_112', 'Weyburn', 'Saskatchewan', 'SK', 11143)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_113', 'Lloydminster', 'Alberta', 'AB', 36747)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_114', 'Lloydminster', 'Alberta', 'AB', 20550)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_115', 'Lloydminster', 'Saskatchewan', 'SK', 16197)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_116', 'Medicine Hat', 'Alberta', 'AB', 80126)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_117', 'Brooks', 'Alberta', 'AB', 24966)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_119', 'Okotoks', 'Alberta', 'AB', 31764)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_120', 'High River', 'Alberta', 'AB', 14391)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_122', 'Strathmore', 'Alberta', 'AB', 14468)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_123', 'Canmore', 'Alberta', 'AB', 16347)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_125', 'Sylvan Lake', 'Alberta', 'AB', 16477)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_126', 'Lacombe', 'Alberta', 'AB', 12956)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_127', 'Camrose', 'Alberta', 'AB', 18801)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_129', 'Cold Lake', 'Alberta', 'AB', 14108)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_130', 'Grande Prairie', 'Alberta', 'AB', 68350)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_131', 'Wood Buffalo', 'Alberta', 'AB', 76649)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_132', 'Wetaskiwin', 'Alberta', 'AB', 12935)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_133', 'Cranbrook', 'British Columbia', 'BC', 28052)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_134', 'Nelson', 'British Columbia', 'BC', 20254)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_135', 'Penticton', 'British Columbia', 'BC', 47449)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_137', 'Vernon', 'British Columbia', 'BC', 68961)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_138', 'Salmon Arm', 'British Columbia', 'BC', 19997)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_143', 'Squamish', 'British Columbia', 'BC', 25179)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_145', 'Duncan', 'British Columbia', 'BC', 49500)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_147', 'Parksville', 'British Columbia', 'BC', 31809)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_148', 'Port Alberni', 'British Columbia', 'BC', 27771)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_149', 'Courtenay', 'British Columbia', 'BC', 61865)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_150', 'Campbell River', 'British Columbia', 'BC', 43529)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_151', 'Powell River', 'British Columbia', 'BC', 17931)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_152', 'Williams Lake', 'British Columbia', 'BC', 19596)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_153', 'Quesnel', 'British Columbia', 'BC', 24115)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_154', 'Prince Rupert', 'British Columbia', 'BC', 13828)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_155', 'Terrace', 'British Columbia', 'BC', 17682)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_156', 'Prince George', 'British Columbia', 'BC', 96207)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_157', 'Dawson Creek', 'British Columbia', 'BC', 13784)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_158', 'Fort St. John', 'British Columbia', 'BC', 29730)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_159', 'Whitehorse', 'Yukon', 'YT', 35372)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);
INSERT INTO cities_meta (cma_code, city_name, province, province_abbr, population_2021)
VALUES ('CA_160', 'Yellowknife', 'Northwest Territories', 'NT', 22983)
ON DUPLICATE KEY UPDATE population_2021 = VALUES(population_2021);

-- ── cities_safety (only cities covered by table 35-10-0026-01) ─────────────
INSERT INTO cities_safety (cma_code, crime_severity_index, source_notes, data_date)
VALUES ('CA_52', 52.76, 'StatsCan WDS 35-10-0026-01 (2025-01-01)', '2026-08-12')
ON DUPLICATE KEY UPDATE crime_severity_index = VALUES(crime_severity_index), source_notes = VALUES(source_notes), data_date = VALUES(data_date);
INSERT INTO cities_safety (cma_code, crime_severity_index, source_notes, data_date)
VALUES ('CA_53', 50.61, 'StatsCan WDS 35-10-0026-01 (2025-01-01)', '2026-08-12')
ON DUPLICATE KEY UPDATE crime_severity_index = VALUES(crime_severity_index), source_notes = VALUES(source_notes), data_date = VALUES(data_date);
INSERT INTO cities_safety (cma_code, crime_severity_index, source_notes, data_date)
VALUES ('CA_54', 60.55, 'StatsCan WDS 35-10-0026-01 (2025-01-01)', '2026-08-12')
ON DUPLICATE KEY UPDATE crime_severity_index = VALUES(crime_severity_index), source_notes = VALUES(source_notes), data_date = VALUES(data_date);

