#!/usr/bin/env node
/**
 * Generate PDF Report Cards for all ridings.
 * Reads from api/mps.json. Outputs to reports/ridings/.
 * Usage: node generate-reports.js
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const REPORTS_DIR = path.join(__dirname, '..', 'reports');
const API_DIR = path.join(__dirname, '..', 'api');

const COLORS = {
  red: '#D52B1E', gold: '#FFD700', text: '#1A1A1A', sub: '#5C5C5C',
  muted: '#8C8C8C', bg: '#F8F6F1', white: '#FFFFFF', border: '#E8E4DC',
  gradeA: '#1B5E20', gradeB: '#2E7D32', gradeC: '#B45309', gradeD: '#C2410C', gradeF: '#B71C1C',
};

function gradeColor(grade) {
  if (!grade) return COLORS.muted;
  if (grade.startsWith('A')) return COLORS.gradeA;
  if (grade.startsWith('B')) return COLORS.gradeB;
  if (grade.startsWith('C')) return COLORS.gradeC;
  if (grade.startsWith('D')) return COLORS.gradeD;
  return COLORS.gradeF;
}

// Category labels (no emoji — PDFKit can't render them)
const CAT_LABELS = {
  performance:  'MP Performance',
  investment:   'Federal Investment',
  electoral:    'Electoral Health',
  demographics: 'Demographics',
  expenses:     'MP Expenses',
  transfers:    'Federal Transfers',
};
const CAT_WEIGHTS = {
  investment: '50%', transfers: '35%', expenses: '15%',
  performance: 'Context', electoral: 'Context', demographics: 'Context',
};

function drawScoreBar(doc, x, y, width, score, label) {
  const barH = 16;
  doc.roundedRect(x, y, width, barH, 3).fill('#EEEBE5');
  if (score != null && score > 0) {
    const fillW = Math.max(6, (score / 100) * width);
    const color = score >= 80 ? COLORS.gradeA : score >= 60 ? COLORS.gradeB : score >= 40 ? COLORS.gradeC : score >= 20 ? COLORS.gradeD : COLORS.gradeF;
    doc.roundedRect(x, y, fillW, barH, 3).fill(color);
  }
  doc.fontSize(9).fillColor(COLORS.white).font('Helvetica-Bold')
     .text(label, x + 6, y + 3, { width: width - 40 });
  if (score != null) {
    doc.fontSize(9).fillColor(COLORS.text).text(`${score}`, x + width - 30, y + 3, { width: 26, align: 'right' });
  }
}

function generateRidingPDF(riding, allRidings, outputPath, { voteRecords, spendingData, expenseData } = {}) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 50, bufferPages: true });
  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  const W = 512; // 612 - 2*50
  const cats = riding.categories;

  // ════════ PAGE 1: COVER ════════════════════════════════════════════════
  doc.rect(0, 0, 612, 8).fill(COLORS.red);

  // Brand wordmark
  doc.fontSize(12).fillColor(COLORS.muted).font('Helvetica')
     .text('BANG FOR YOUR DUCK', 50, 50, { align: 'center', width: W, characterSpacing: 3 });

  // Horizontal rule
  doc.moveTo(230, 72).lineTo(382, 72).stroke(COLORS.border);

  // Riding name
  doc.fontSize(32).fillColor(COLORS.text).font('Helvetica-Bold')
     .text(riding.name, 50, 88, { align: 'center', width: W });

  // MP + party + province
  const mpLine = `${riding.mpName || 'Vacant'}  |  ${riding.mpParty || ''}  |  ${riding.province}`;
  doc.fontSize(13).fillColor(COLORS.sub).font('Helvetica')
     .text(mpLine, 50, 135, { align: 'center', width: W });

  // Grade circle
  const gradeY = 175;
  doc.circle(306, gradeY + 50, 55).fill(gradeColor(riding.grade));
  doc.fontSize(52).fillColor(COLORS.white).font('Helvetica-Bold')
     .text(riding.grade, 251, gradeY + 20, { width: 110, align: 'center' });

  doc.fontSize(14).fillColor(COLORS.text).font('Helvetica')
     .text(`${riding.composite} / 100`, 50, gradeY + 115, { align: 'center', width: W });
  doc.fontSize(10).fillColor(COLORS.muted)
     .text('PERFORMANCE COMPOSITE', 50, gradeY + 135, { align: 'center', width: W, characterSpacing: 2 });

  // Duck score
  if (riding.duckScore != null) {
    doc.moveTo(230, gradeY + 160).lineTo(382, gradeY + 160).stroke(COLORS.border);
    doc.fontSize(11).fillColor(COLORS.sub)
       .text(`Bang for Your Duck:  ${riding.duckGrade}  |  ${riding.duckScore}/100`, 50, gradeY + 172, { align: 'center', width: W });
    doc.fontSize(9).fillColor(COLORS.muted)
       .text('Value for federal tax dollars generated by this riding', 50, gradeY + 190, { align: 'center', width: W });
  }

  // Population
  if (riding.population) {
    doc.fontSize(10).fillColor(COLORS.muted)
       .text(`Population: ${riding.population.toLocaleString('en-CA')}`, 50, gradeY + 218, { align: 'center', width: W });
  }

  // Report meta + sources
  doc.fontSize(9).fillColor(COLORS.muted)
     .text(`Report generated ${new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })}`, 50, gradeY + 240, { align: 'center', width: W });
  doc.fontSize(7).fillColor(COLORS.muted)
     .text('Sources: Elections Canada | OpenParliament.ca | Infrastructure Canada | House of Commons Disclosure | StatsCan Census 2021', 50, gradeY + 260, { align: 'center', width: W })
     .text('Governments publish the data. We collect it, score it, and present it in one place.', 50, gradeY + 274, { align: 'center', width: W });

  doc.fontSize(8).fillColor(COLORS.muted)
     .text('bangforyourduck.ca | Where does your tax loonie go?', 50, 720, { align: 'center', width: W });
  doc.fontSize(7).fillColor(COLORS.muted)
     .text('Full methodology & terms: bangforyourduck.ca/methodology', 50, 735, { align: 'center', width: W });

  // ════════ PAGE 2: ABOUT THIS REPORT ═══════════════════════════════════
  doc.addPage();
  doc.rect(0, 0, 612, 8).fill(COLORS.red);

  doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('About This Report', 50, 30);
  doc.moveTo(50, 58).lineTo(562, 58).stroke(COLORS.border);

  let mY = 70;

  // Editorial disclaimer
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Editorial Disclaimer', 50, mY);
  mY += 18;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('Bang for Your Duck is an independent, nonpartisan editorial project. Scores and grades represent opinions based on publicly available government data. This report is not legal, financial, or political advice. We are not affiliated with any political party, government body, or lobby group.', 50, mY, { width: W });
  mY += 50;

  // How we grade
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('How We Grade', 50, mY);
  mY += 18;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('This report grades your riding \u2014 not your MP personally \u2014 on measurable dollar flows: federal investment received (50%), federal transfers allocated (35%), and the cost of representation (15%). Context categories like MP Work, Electoral Health, and Demographics are shown but do not factor into the composite grade.', 50, mY, { width: W });
  mY += 55;

  // What we don't measure
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('What We Don\u2019t Measure', 50, mY);
  mY += 18;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('No model captures the full picture of parliamentary representation. Constituency casework, committee influence, speech quality, legislative amendments, caucus advocacy, and riding-level service delivery are important but not quantifiable from publicly available data at scale. Our scores are a starting point for conversation, not the final word.', 50, mY, { width: W });
  mY += 55;

  // Structural factors
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Structural Factors', 50, mY);
  mY += 18;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('Scores are affected by factors outside any MP\u2019s direct control: geography (travel costs are higher for remote ridings), government vs. opposition status (governing MPs have more influence over spending), provincial transfer formulas (all ridings in a province share the same transfer score), population density, and urban vs. rural characteristics. A low score is a statement about federal spending patterns, not about any MP\u2019s dedication.', 50, mY, { width: W });
  mY += 70;

  // For MPs
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('For MPs and Staff', 50, mY);
  mY += 18;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('We grade ridings, not individuals. If any data in this report is inaccurate, we want to know. Email corrections@bangforyourduck.ca with the riding name, the data point in question, the correct figure, and supporting documentation. We review all correction requests and will update scores if warranted.', 50, mY, { width: W });
  mY += 50;

  // Data sources
  doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Data Sources', 50, mY);
  mY += 18;
  doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica');
  const aboutSources = [
    'Infrastructure Canada Open Data (infrastructure.gc.ca)',
    'OpenParliament.ca \u2014 Session 45-1',
    'Elections Canada \u2014 45th General Election',
    'House of Commons Proactive Disclosure (ourcommons.ca)',
    'Statistics Canada \u2014 2021 Census of Population',
    'Department of Finance \u2014 Major Federal Transfers 2023-24',
  ];
  for (const src of aboutSources) {
    doc.text('  \u2022  ' + src, 50, mY, { width: W });
    mY += 13;
  }

  // Full methodology link
  mY += 12;
  doc.fontSize(10).fillColor(COLORS.red).font('Helvetica-Bold')
     .text('Full methodology: bangforyourduck.ca/methodology', 50, mY, { align: 'center', width: W, link: 'https://bangforyourduck.ca/methodology/' });

  doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica')
     .text('bangforyourduck.ca  |  Independent \u00b7 Nonpartisan \u00b7 Community-supported', 50, 720, { align: 'center', width: W });

  // ════════ PAGE 3: SCORE BREAKDOWN ═════════════════════════════════════
  doc.addPage();
  doc.rect(0, 0, 612, 8).fill(COLORS.red);

  doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Score Breakdown', 50, 30);
  doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
     .text(`${riding.name}  |  ${riding.mpName || 'Vacant'}`, 50, 58);

  doc.moveTo(50, 78).lineTo(562, 78).stroke(COLORS.border);

  const categories = ['investment', 'transfers', 'expenses', 'performance', 'electoral', 'demographics'];
  let catY = 95;

  for (const key of categories) {
    const data = cats[key];
    const score = data?.score;
    const grade = data?.grade || 'N/A';

    doc.fontSize(13).fillColor(COLORS.text).font('Helvetica-Bold')
       .text(CAT_LABELS[key], 50, catY);
    doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
       .text(`Weight: ${CAT_WEIGHTS[key]}`, 400, catY + 2, { width: 162, align: 'right' });

    drawScoreBar(doc, 50, catY + 22, W, score, `${grade}  |  ${score != null ? score + '/100' : 'No data'}`);

    let metricsY = catY + 46;
    doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica');

    if (key === 'performance' && data) {
      const parts = [];
      if (data.voteParticipationPct != null) parts.push(`Votes: ${data.voteParticipationPct}%`);
      if (data.billsIntroduced != null) parts.push(`Bills: ${data.billsIntroduced}`);
      if (data.speechesCount != null) parts.push(`Speeches: ${data.speechesCount}`);
      if (data.isOpposition) parts.push('(+5 opposition bonus)');
      if (parts.length) doc.text(parts.join('   |   '), 60, metricsY);
      metricsY += parts.length ? 14 : 0;
    } else if (key === 'electoral' && data) {
      const parts = [];
      if (data.voterTurnoutPct != null) parts.push(`Turnout: ${data.voterTurnoutPct}%`);
      if (data.marginOfVictoryPct != null) parts.push(`Margin: ${data.marginOfVictoryPct}%`);
      if (data.candidatesCount != null) parts.push(`Candidates: ${data.candidatesCount}`);
      if (parts.length) doc.text(parts.join('   |   '), 60, metricsY);
      metricsY += parts.length ? 14 : 0;
    } else if (key === 'demographics' && data) {
      const parts = [];
      if (data.medianHouseholdIncome != null) parts.push(`Income: $${data.medianHouseholdIncome.toLocaleString('en-CA')}`);
      if (data.unemploymentRate != null) parts.push(`Unemployment: ${data.unemploymentRate}%`);
      if (data.postsecondaryRate != null) parts.push(`Post-secondary: ${data.postsecondaryRate}%`);
      if (parts.length) doc.text(parts.join('   |   '), 60, metricsY);
      metricsY += parts.length ? 14 : 0;
    } else if (key === 'transfers' && data) {
      const parts = [];
      if (data.totalTransfersPerCapita != null) parts.push(`Total: $${data.totalTransfersPerCapita}/person`);
      if (data.chtPerCapita != null) parts.push(`CHT: $${data.chtPerCapita}`);
      if (data.equalizationPerCapita != null) parts.push(data.equalizationPerCapita > 0 ? `Equalization: $${data.equalizationPerCapita}` : 'No equalization');
      if (parts.length) doc.text(parts.join('   |   '), 60, metricsY);
      metricsY += parts.length ? 14 : 0;
    }

    catY = metricsY + 16;
    doc.moveTo(50, catY - 6).lineTo(562, catY - 6).stroke('#F0EDE8');
  }

  // Formula arithmetic
  const invS = cats.investment?.score ?? 0;
  const traS = cats.transfers?.score ?? 0;
  const expS = cats.expenses?.score ?? 0;
  const invC = Math.round(invS * 0.50);
  const traC = Math.round(traS * 0.35);
  const expC = Math.round(expS * 0.15);
  catY += 4;
  doc.moveTo(50, catY).lineTo(562, catY).lineWidth(1.5).stroke(COLORS.text);
  catY += 10;
  doc.fontSize(10).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Grade Calculation:', 50, catY);
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text(`(${invS} x 0.50) + (${traS} x 0.35) + (${expS} x 0.15) = ${invC} + ${traC} + ${expC} = ${riding.composite}/100`, 180, catY + 1);
  catY += 16;
  doc.fontSize(8).fillColor(COLORS.muted)
     .text('Grade = dollars flowing into your riding vs the cost of representation. Performance, electoral, and demographics are shown as context only.', 50, catY, { width: W });

  doc.fontSize(8).fillColor(COLORS.muted)
     .text('bangforyourduck.ca  |  Community-supported · Nonpartisan · bangforyourduck.ca', 50, 720, { align: 'center', width: W });

  // ════════ PAGE 3: HOW YOUR MP VOTED ════════════════════════════════════
  if (voteRecords) {
    const ridingKey = riding.name + '|' + riding.province;
    const record = voteRecords[ridingKey];
    if (record && record.votes) {
      doc.addPage();
      doc.rect(0, 0, 612, 8).fill(COLORS.red);

      doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
         .text('How Your MP Voted', 50, 30);
      doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
         .text(`${riding.mpName}  |  ${record.voted} of ${record.totalVotes || record.total || 94} votes attended  |  ${record.participationPct || Math.round(record.voted / (record.totalVotes || record.total || 94) * 100)}% participation`, 50, 58);
      doc.moveTo(50, 78).lineTo(562, 78).stroke(COLORS.border);

      let vY = 90;
      const pageBottom = 700;

      // Table header
      function drawVoteHeader() {
        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica-Bold');
        doc.text('#', 50, vY); doc.text('DATE', 70, vY); doc.text('BILL', 135, vY); doc.text('DESCRIPTION', 185, vY); doc.text('RESULT', 420, vY); doc.text('VOTE', 490, vY);
        vY += 14;
        doc.font('Helvetica');
      }
      drawVoteHeader();

      for (const v of record.votes) {
        // Page break if needed
        if (vY > pageBottom) {
          doc.fontSize(8).fillColor(COLORS.muted)
             .text('bangforyourduck.ca  |  Community-supported · Nonpartisan', 50, 720, { align: 'center', width: W });
          doc.addPage();
          doc.rect(0, 0, 612, 8).fill(COLORS.red);
          doc.fontSize(14).fillColor(COLORS.text).font('Helvetica-Bold')
             .text('How Your MP Voted (continued)', 50, 25);
          vY = 50;
          drawVoteHeader();
        }

        const ballotColor = v.ballot === 'Yes' ? COLORS.gradeA : v.ballot === 'No' ? COLORS.gradeF : v.ballot === 'Paired' ? COLORS.muted : '#CC8800';
        const desc = v.description || v.label || '';
        const voteLink = v.number ? `https://openparliament.ca/votes/45-1/${v.number}/` : null;
        doc.fontSize(8).fillColor('#1565C0');
        doc.text(String(v.number || ''), 50, vY, { width: 18, link: voteLink }); // clickable link
        doc.fillColor(COLORS.muted).text(v.date ? v.date.substring(5) : '', 70, vY, { width: 60 });
        doc.fillColor(COLORS.text).text(v.bill || '—', 135, vY, { width: 45 });
        doc.fontSize(7).fillColor(COLORS.sub).text(desc.substring(0, 40), 185, vY, { width: 230 });
        doc.fontSize(7).fillColor(COLORS.muted).text(v.result || '', 420, vY, { width: 60 });
        doc.fontSize(9).fillColor(ballotColor).font('Helvetica-Bold').text(v.ballot, 490, vY, { width: 60 });
        doc.font('Helvetica');
        vY += 14;
      }

      doc.fontSize(8).fillColor(COLORS.muted)
         .text(`Source: OpenParliament.ca  |  Session 45-1  |  All ${record.totalVotes || record.total || 94} recorded votes`, 50, vY + 10, { width: W });
      doc.text('bangforyourduck.ca  |  Community-supported · Nonpartisan', 50, 720, { align: 'center', width: W });
    }
  }

  // ════════ PAGE 4: FEDERAL SPENDING IN YOUR RIDING ════════════════════
  if (spendingData) {
    const rs = spendingData[riding.ridingCode];
    if (rs && rs.totalFederal > 0) {
      doc.addPage();
      doc.rect(0, 0, 612, 8).fill(COLORS.red);

      // Per-capita ranking
      const allSpending = Object.entries(spendingData)
        .filter(([,v]) => v.totalFederal > 0)
        .map(([code, v]) => {
          const r = allRidings.find(r => r.ridingCode === code);
          const pop = r?.population || 100000;
          return { code, perCapita: v.totalFederal / pop };
        })
        .sort((a, b) => b.perCapita - a.perCapita);
      const spendRank = allSpending.findIndex(s => s.code === riding.ridingCode) + 1;

      doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
         .text('Federal Spending in Your Riding', 50, 30);
      doc.fontSize(14).fillColor(COLORS.gradeA).font('Helvetica-Bold')
         .text(`$${(rs.totalFederal / 1e6).toFixed(1)}M total federal investment`, 50, 58);
      doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
         .text(`Ranked #${spendRank} of ${allSpending.length} ridings by per-capita investment  |  Infrastructure Canada`, 50, 78);
      doc.moveTo(50, 96).lineTo(562, 96).stroke(COLORS.border);

      // Category breakdown
      if (rs.byCategory && Object.keys(rs.byCategory).length > 0) {
        let cY = 108;
        doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
           .text('Spending by Category', 50, cY);
        cY += 20;

        const sortedCats = Object.entries(rs.byCategory)
          .filter(([,v]) => v > 0)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 8);

        for (const [cat, amount] of sortedCats) {
          const barW = Math.max(4, (amount / rs.totalFederal) * 350);
          const pct = Math.round(amount / rs.totalFederal * 100);
          doc.roundedRect(50, cY, 350, 12, 2).fill('#EEEBE5');
          doc.roundedRect(50, cY, barW, 12, 2).fill(COLORS.red);
          doc.fontSize(8).fillColor(COLORS.text).font('Helvetica')
             .text(cat, 410, cY + 1, { width: 120 });
          doc.text('$' + (amount / 1e6).toFixed(1) + 'M (' + pct + '%)', 530, cY + 1, { width: 50 });
          cY += 17;
        }
        cY += 10;
        doc.moveTo(50, cY).lineTo(562, cY).stroke('#F0EDE8');
        cY += 12;

        // Project list
        doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
           .text('Largest Projects', 50, cY);
        cY += 18;

        doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica-Bold');
        doc.text('PROJECT', 50, cY); doc.text('FEDERAL $', 380, cY); doc.text('CATEGORY', 450, cY);
        cY += 14;

        doc.font('Helvetica');
        for (const p of rs.projects.slice(0, 6)) {
          doc.fontSize(8).fillColor(COLORS.text);
          doc.text(p.title.substring(0, 55), 50, cY, { width: 320 });
          doc.fillColor(COLORS.gradeA).text('$' + (p.federal / 1e6).toFixed(1) + 'M', 380, cY, { width: 60 });
          doc.fontSize(7).fillColor(COLORS.muted).text((p.category || '').substring(0, 25), 450, cY, { width: 110 });
          cY += 12;
          // Recipient line
          if (p.recipient) {
            doc.fontSize(6).fillColor(COLORS.muted).text('Recipient: ' + p.recipient.substring(0, 60), 60, cY);
            cY += 10;
          }
          cY += 4;
        }

        if (rs.projects.length > 6) {
          doc.fontSize(8).fillColor(COLORS.muted).text('+ ' + (rs.projects.length - 6) + ' more projects', 50, cY + 5);
        }
      }

      doc.fontSize(7).fillColor(COLORS.muted)
         .text('Source: Infrastructure Canada Open Data (infrastructure.gc.ca) | All federally funded projects', 50, 700, { width: W });
      doc.fontSize(8).fillColor(COLORS.muted)
         .text('bangforyourduck.ca | Where does your tax loonie go?', 50, 720, { align: 'center', width: W });
    }
  }

  // ════════ PAGE 5: MP EXPENSES ═════════════════════════════════════════
  if (expenseData) {
    const exp = expenseData[riding.ridingCode];
    if (exp && exp.totalQ3 > 0) {
      doc.addPage();
      doc.rect(0, 0, 612, 8).fill(COLORS.red);

      doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
         .text('MP Expense Report', 50, 30);
      doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
         .text(`${exp.mpName}  |  Q3 2025-26 (Oct-Dec 2025)  |  House of Commons Proactive Disclosure`, 50, 58);
      doc.moveTo(50, 78).lineTo(562, 78).stroke(COLORS.border);

      const expItems = [
        { label: 'Staff Salaries',     amount: exp.salaries,     pct: exp.totalQ3 > 0 ? Math.round(exp.salaries / exp.totalQ3 * 100) : 0 },
        { label: 'Travel',             amount: exp.travel,       pct: exp.totalQ3 > 0 ? Math.round(exp.travel / exp.totalQ3 * 100) : 0 },
        { label: 'Hospitality',        amount: exp.hospitality,  pct: exp.totalQ3 > 0 ? Math.round(exp.hospitality / exp.totalQ3 * 100) : 0 },
        { label: 'Contracts',          amount: exp.contracts,    pct: exp.totalQ3 > 0 ? Math.round(exp.contracts / exp.totalQ3 * 100) : 0 },
      ];

      let eY = 95;
      for (const item of expItems) {
        doc.fontSize(12).fillColor(COLORS.text).font('Helvetica-Bold')
           .text(item.label, 50, eY);
        doc.fontSize(12).fillColor(item.amount > 0 ? COLORS.text : COLORS.muted)
           .text('$' + Math.abs(item.amount).toLocaleString('en-CA'), 300, eY, { width: 120, align: 'right' });
        doc.fontSize(9).fillColor(COLORS.muted).font('Helvetica')
           .text(item.pct + '% of total', 430, eY + 2);

        // Bar
        const barW = Math.max(0, (Math.abs(item.amount) / exp.totalQ3) * 400);
        doc.roundedRect(50, eY + 20, 400, 10, 2).fill('#EEEBE5');
        if (barW > 0) doc.roundedRect(50, eY + 20, barW, 10, 2).fill(COLORS.red);
        eY += 42;
      }

      doc.moveTo(50, eY).lineTo(562, eY).stroke(COLORS.text);
      eY += 8;
      doc.fontSize(14).fillColor(COLORS.text).font('Helvetica-Bold')
         .text('Q3 Total:', 50, eY);
      doc.text('$' + exp.totalQ3.toLocaleString('en-CA'), 300, eY, { width: 120, align: 'right' });
      doc.fontSize(10).fillColor(COLORS.muted).font('Helvetica')
         .text('Annualized estimate: ~$' + exp.annualEstimate.toLocaleString('en-CA'), 50, eY + 22);

      doc.fontSize(8).fillColor(COLORS.muted)
         .text('Source: ourcommons.ca/ProactiveDisclosure  |  Q3 2025-26', 50, eY + 50, { width: W });
      doc.text('bangforyourduck.ca  |  Community-supported · Nonpartisan · bangforyourduck.ca', 50, 720, { align: 'center', width: W });
    }
  }

  // ════════ PAGE 6: COMPARISON + QUESTIONS ═══════════════════════════════
  doc.addPage();
  doc.rect(0, 0, 612, 8).fill(COLORS.red);

  doc.fontSize(22).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('How You Compare', 50, 30);

  const sorted = [...allRidings].sort((a, b) => b.composite - a.composite);
  const rank = sorted.findIndex(r => r.ridingCode === riding.ridingCode) + 1;
  const provRidings = sorted.filter(r => r.province === riding.province);
  const provRank = provRidings.findIndex(r => r.ridingCode === riding.ridingCode) + 1;

  doc.fontSize(13).fillColor(COLORS.text).font('Helvetica')
     .text(`National rank:  #${rank} of ${allRidings.length}`, 50, 62)
     .text(`Provincial rank (${riding.province}):  #${provRank} of ${provRidings.length}`, 50, 80);

  // Comparable ridings table
  doc.fontSize(16).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Comparable Ridings', 50, 110);

  const comparables = provRidings
    .filter(r => r.ridingCode !== riding.ridingCode)
    .sort((a, b) => Math.abs(a.composite - riding.composite) - Math.abs(b.composite - riding.composite))
    .slice(0, 5);

  let tY = 135;
  doc.fontSize(8).fillColor(COLORS.muted).font('Helvetica-Bold');
  doc.text('RIDING', 50, tY); doc.text('MP', 230, tY); doc.text('PARTY', 380, tY);
  doc.text('GRADE', 460, tY); doc.text('SCORE', 510, tY);
  tY += 14;
  doc.moveTo(50, tY).lineTo(562, tY).stroke(COLORS.border);
  tY += 6;

  // Highlighted row (your riding)
  doc.rect(46, tY - 3, W + 8, 18).fill('#FFF0EF');
  doc.fontSize(9).fillColor(COLORS.red).font('Helvetica-Bold');
  doc.text(riding.name.substring(0, 32), 50, tY);
  doc.text((riding.mpName || '').substring(0, 22), 230, tY);
  doc.text(riding.mpParty || '', 380, tY);
  doc.text(riding.grade, 460, tY);
  doc.text(`${riding.composite}`, 510, tY);
  tY += 22;

  doc.font('Helvetica').fillColor(COLORS.text);
  for (const c of comparables) {
    doc.fontSize(9);
    doc.text(c.name.substring(0, 32), 50, tY);
    doc.text((c.mpName || '').substring(0, 22), 230, tY);
    doc.text(c.mpParty || '', 380, tY);
    doc.fillColor(gradeColor(c.grade)).text(c.grade, 460, tY);
    doc.fillColor(COLORS.text).text(`${c.composite}`, 510, tY);
    tY += 18;
  }

  // Questions to ask your MP
  tY += 30;
  doc.fontSize(16).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('Questions to Ask Your MP', 50, tY);
  tY += 25;
  doc.fontSize(10).fillColor(COLORS.sub).font('Helvetica');

  const questions = [];
  if (!cats.performance?.score || cats.performance.score < 50)
    questions.push('How many House votes have you attended this session, and what is your participation rate compared to other MPs?');
  if (!cats.investment?.score || cats.investment.score < 50)
    questions.push('What federal infrastructure grants has this riding received in the past 3 years, and how does that compare to similar ridings?');
  if (cats.electoral?.voterTurnoutPct && cats.electoral.voterTurnoutPct < 65)
    questions.push(`Voter turnout in this riding was ${cats.electoral.voterTurnoutPct}%. What are you doing to encourage democratic participation?`);
  if (cats.demographics?.unemploymentRate && cats.demographics.unemploymentRate > 7)
    questions.push(`The unemployment rate here is ${cats.demographics.unemploymentRate}%. What federal programs are you advocating for to support job creation?`);
  if (cats.transfers?.equalizationPerCapita != null && cats.transfers.equalizationPerCapita === 0)
    questions.push('This province does not receive equalization payments. How are you ensuring federal investment still flows back to our community?');
  questions.push('What is your top priority for this riding in the next parliamentary session, and how will you measure success?');

  for (const q of questions) {
    const h = doc.heightOfString(`   ${q}`, { width: W - 20 });
    doc.text(`   ${q}`, 55, tY, { width: W - 20 });
    // Bullet
    doc.circle(60, tY + 5, 2.5).fill(COLORS.red);
    tY += h + 10;
  }

  // MP contact block
  tY += 20;
  doc.moveTo(50, tY).lineTo(562, tY).stroke(COLORS.border);
  tY += 12;
  doc.fontSize(11).fillColor(COLORS.text).font('Helvetica-Bold')
     .text('MP or staff? Help us improve accuracy.', 50, tY);
  tY += 16;
  doc.fontSize(9).fillColor(COLORS.sub).font('Helvetica')
     .text('If any data in this report is inaccurate, visit bangforyourduck.ca/methodology or email corrections@bangforyourduck.ca with the riding name, the data point in question, and supporting documentation.', 50, tY, { width: W });

  doc.fontSize(8).fillColor(COLORS.muted)
     .text('bangforyourduck.ca  |  Independent \u00b7 Nonpartisan \u00b7 Community-supported', 50, 720, { align: 'center', width: W });

  doc.end();
  return new Promise(resolve => stream.on('finish', resolve));
}

async function main() {
  console.log('[reports] Reading JSON data...');
  const mpsData = JSON.parse(fs.readFileSync(path.join(API_DIR, 'mps.json'), 'utf8'));
  const ridings = mpsData.ridings;

  let voteRecords = null, spendingData = null, expenseData = null;
  try { voteRecords = JSON.parse(fs.readFileSync(path.join(API_DIR, 'vote-records.json'), 'utf8')); } catch {}
  try { spendingData = JSON.parse(fs.readFileSync(path.join(API_DIR, 'riding-spending.json'), 'utf8')); } catch {}
  try { expenseData = JSON.parse(fs.readFileSync(path.join(API_DIR, 'mp-expenses.json'), 'utf8')); } catch {}

  console.log(`[reports] ${ridings.length} ridings | votes: ${voteRecords ? Object.keys(voteRecords).length : 0} | spending: ${spendingData ? Object.keys(spendingData).length : 0} | expenses: ${expenseData ? Object.keys(expenseData).length : 0}`);

  const ridingsDir = path.join(REPORTS_DIR, 'ridings');
  fs.mkdirSync(ridingsDir, { recursive: true });

  console.log('[reports] Generating PDFs...');
  let count = 0;
  for (const riding of ridings) {
    const slug = riding.name.replace(/[^a-zA-Z0-9\u00C0-\u024F\u2014\u2013\- ]/g, '').replace(/\s+/g, '-').toLowerCase();
    const filename = `${riding.ridingCode}-${slug}.pdf`;
    await generateRidingPDF(riding, ridings, path.join(ridingsDir, filename), { voteRecords, spendingData, expenseData });
    count++;
    if (count % 50 === 0) console.log(`  [${count}/${ridings.length}]`);
  }

  console.log(`\n[reports] Done: ${count} PDFs in reports/ridings/`);

  const index = ridings.map(r => ({
    code: r.ridingCode,
    name: r.name,
    file: `${r.ridingCode}-${r.name.replace(/[^a-zA-Z0-9\u00C0-\u024F\u2014\u2013\- ]/g, '').replace(/\s+/g, '-').toLowerCase()}.pdf`,
  }));
  fs.writeFileSync(path.join(REPORTS_DIR, 'index.json'), JSON.stringify(index));
}

main().catch(err => { console.error('[reports] Fatal:', err); process.exit(1); });
